import { Market, Placement } from './types';

export const MARKETS: Market[] = [
    // AME
    { code: 'US', name: 'Estados Unidos', selector: 'US (Estados Unidos)', region: 'AME', defaultLang: 'en' },
    { code: 'CA', name: 'Canadá', selector: 'CA (Canadá)', region: 'AME', defaultLang: 'en' },
    { code: 'MX', name: 'México', selector: 'MX (México)', region: 'AME', defaultLang: 'es' },
    { code: 'CR', name: 'Costa Rica', selector: 'CR (Costa Rica)', region: 'AME', defaultLang: 'es' },
    { code: 'LTM', name: 'Latam', selector: 'LTM (Latam)', region: 'AME', defaultLang: 'es' },
    { code: 'JM', name: 'Jamaica', selector: 'JM (Jamaica)', region: 'AME', defaultLang: 'en' },
    { code: 'PA', name: 'Panamá', selector: 'PA (Panamá)', region: 'AME', defaultLang: 'es' },
    { code: 'DO', name: 'Rep. Dominicana', selector: 'DO (Rep. Dominicana)', region: 'AME', defaultLang: 'es' },
    { code: 'BR', name: 'Brasil', selector: 'BR (Brasil)', region: 'AME', defaultLang: 'pt' },
    { code: 'CO', name: 'Colombia', selector: 'CO (Colombia)', region: 'AME', defaultLang: 'es' },
    { code: 'AR', name: 'Argentina', selector: 'AR (Argentina)', region: 'AME', defaultLang: 'es' },
    { code: 'CL', name: 'Chile', selector: 'CL (Chile)', region: 'AME', defaultLang: 'es' },

    // EMEA
    { code: 'ES', name: 'España', selector: 'ES (España)', region: 'EMEA', defaultLang: 'es' },
    { code: 'GB', name: 'Reino Unido', selector: 'GB (Reino Unido)', region: 'EMEA', defaultLang: 'en' },
    { code: 'DE', name: 'Alemania', selector: 'DE (Alemania)', region: 'EMEA', defaultLang: 'de' },
    { code: 'CH', name: 'Suiza', selector: 'CH (Suiza)', region: 'EMEA', defaultLang: 'de' },
    { code: 'IE', name: 'Irlanda', selector: 'IE (Irlanda)', region: 'EMEA', defaultLang: 'en' },
    { code: 'FR', name: 'Francia', selector: 'FR (Francia)', region: 'EMEA', defaultLang: 'fr' },
    { code: 'IT', name: 'Italia', selector: 'IT (Italia)', region: 'EMEA', defaultLang: 'it' },
    { code: 'PT', name: 'Portugal', selector: 'PT (Portugal)', region: 'EMEA', defaultLang: 'pt' },
    { code: 'ESC', name: 'Escocia', selector: 'ESC (Escocia)', region: 'EMEA', defaultLang: 'en' },
    { code: 'BE-FR', name: 'Bélgica (FR)', selector: 'BE-FR (Bélgica FR)', region: 'EMEA', defaultLang: 'fr' },
    { code: 'BE-NL', name: 'Bélgica (NL)', selector: 'BE-NL (Bélgica NL)', region: 'EMEA', defaultLang: 'nl' },
    { code: 'NL', name: 'Países Bajos', selector: 'NL (Países Bajos)', region: 'EMEA', defaultLang: 'nl' },
    { code: 'PL', name: 'Polonia', selector: 'PL (Polonia)', region: 'EMEA', defaultLang: 'pl' },
    { code: 'RU', name: 'Rusia', selector: 'RU (Rusia)', region: 'EMEA', defaultLang: 'ru' },

    // APAC
    { code: 'AE', name: 'Emiratos Árabes', selector: 'AE (Emiratos Árabes)', region: 'APAC', defaultLang: 'en' },
    { code: 'AU', name: 'Australia', selector: 'AU (Australia)', region: 'APAC', defaultLang: 'en' },
    { code: 'IN', name: 'India', selector: 'IN (India)', region: 'APAC', defaultLang: 'en' },
    { code: 'LK', name: 'Sri Lanka', selector: 'LK (Sri Lanka)', region: 'APAC', defaultLang: 'en' },
    { code: 'MU', name: 'Mauricio', selector: 'MU (Mauricio)', region: 'APAC', defaultLang: 'en' },
    { code: 'RE', name: 'Reunión', selector: 'RE (Reunión)', region: 'APAC', defaultLang: 'fr' },
    { code: 'ZA', name: 'Sudáfrica', selector: 'ZA (Sudáfrica)', region: 'APAC', defaultLang: 'en' },
    { code: 'QA', name: 'Qatar', selector: 'QA (Qatar)', region: 'APAC', defaultLang: 'en' },
    { code: 'SA', name: 'Arabia Saudí', selector: 'SA (Arabia Saudí)', region: 'APAC', defaultLang: 'ar' },
    { code: 'MA', name: 'Marruecos', selector: 'MA (Marruecos)', region: 'APAC', defaultLang: 'fr' },
    { code: 'SN', name: 'Senegal', selector: 'SN (Senegal)', region: 'APAC', defaultLang: 'fr' },
];

export const PLACEMENTS: Placement[] = [
    { id: 'email_hero_next_gen_clean_image_email', name: 'Email hero Next Gen - Clean image', size: '1100x734', width: 1100, height: 734, format: 'img', channel: 'EMAIL', seconds: 'na', maxFileSize: 150 },
    { id: 'email_hero_next_gen_gif_image_email', name: 'Email hero Next Gen - GIF image', size: '1100x734', width: 1100, height: 734, format: 'gif', channel: 'EMAIL', seconds: 'na', maxFileSize: 150 },
    { id: 'push_app_clean_image_email', name: 'Push APP - Clean image', size: '980x519', width: 980, height: 519, format: 'img', channel: 'EMAIL', seconds: 'na', maxFileSize: 150 },
    { id: 'whatsapp_business_clean_image_max_5mb_email', name: 'WhatsApp Business - Clean image (Max 5MB)', size: '1200x628', width: 1200, height: 628, format: 'img', channel: 'EMAIL', seconds: 'na', maxFileSize: 5000 },
    { id: 'email_signature_email', name: 'Email signature', size: '800x190', width: 800, height: 190, format: 'img', channel: 'EMAIL', seconds: 'na', maxFileSize: 150 },
    { id: 'facebook_mp4_animation_social', name: 'Facebook MP4 Animation', size: '1080x1350', width: 1080, height: 1350, format: 'vid', channel: 'SOCIAL', seconds: 'na', maxFileSize: 150 },
    { id: 'instagram_stories_mp4_animation_stories_safe_zone_social', name: 'Instagram Stories MP4 Animation (Stories Safe Zone)', size: '1080x1920', width: 1080, height: 1920, format: 'vid', channel: 'SOCIAL', seconds: 'na', maxFileSize: 150 },
    { id: 'instagram_reels_mp4_animation_reels_safe_zone_social', name: 'Instagram Reels MP4 Animation (Reels Safe Zone)', size: '1080x1920', width: 1080, height: 1920, format: 'vid', channel: 'SOCIAL', seconds: 'na', maxFileSize: 150 },
    { id: 'facebook_jpg_social', name: 'Facebook JPG', size: '1080x1080', width: 1080, height: 1080, format: 'img', channel: 'SOCIAL', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5120x600', width: 5120, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5160x600', width: 5160, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5300x50', width: 5300, height: 50, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5300x250', width: 5300, height: 250, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5300x600', width: 5300, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5320x50', width: 5320, height: 50, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5468x60', width: 5468, height: 60, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5728x90', width: 5728, height: 90, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'html_display', name: 'HTML', size: '5970x250', width: 5970, height: 250, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '336x280', width: 336, height: 280, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '468x60', width: 468, height: 60, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '728x90', width: 728, height: 90, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '970x90', width: 970, height: 90, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '970x250', width: 970, height: 250, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '320x480', width: 320, height: 480, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'retargeting_cortinillas_jpg_display', name: 'Retargeting Cortinillas JPG', size: '480x320', width: 480, height: 320, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '120x600', width: 120, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '160x600', width: 160, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '300x50', width: 300, height: 50, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '300x250', width: 300, height: 250, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '300x600', width: 300, height: 600, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '320x50', width: 320, height: 50, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '468x60', width: 468, height: 60, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '728x90', width: 728, height: 90, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'amazon_display', name: 'Amazon', size: '970x250', width: 970, height: 250, format: 'img', channel: 'DISPLAY', seconds: 'na', maxFileSize: 150 },
    { id: 'creatividades_nativas_alta_resoluci_n_m_x_600_kb_display_nativo', name: 'Creatividades nativas alta resolución (máx. 600 KB)', size: '1800x1200', width: 1800, height: 1200, format: 'img', channel: 'DISPLAY NATIVO', seconds: 'na', maxFileSize: 600 },
    { id: 'imagen_horizontal_jpg_sem', name: 'Imagen Horizontal JPG', size: '1200x628', width: 1200, height: 628, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 150 },
    { id: 'imagen_cuadrada_jpg_sem', name: 'Imagen Cuadrada JPG', size: '1200x1200', width: 1200, height: 1200, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 150 },
    { id: 'imagen_vertical_jpg_sem', name: 'Imagen Vertical JPG', size: '960x1200', width: 960, height: 1200, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 150 },
    { id: 'imagen_horizontal_jpg_app_max_5_mb_sem', name: 'Imagen Horizontal JPG APP (Max 5 MB)', size: '1200x628', width: 1200, height: 628, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 5000 },
    { id: 'imagen_cuadrada_jpg_app_max_5_mb_sem', name: 'Imagen Cuadrada JPG APP (Max 5 MB)', size: '1200x1200', width: 1200, height: 1200, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 5000 },
    { id: 'imagen_vertical_jpg_app_max_5_mb_sem', name: 'Imagen Vertical JPG APP (Max 5 MB)', size: '1200x1500', width: 1200, height: 1500, format: 'img', channel: 'SEM', seconds: 'na', maxFileSize: 5000 },
    { id: 'jpg_fondo_s_lido_logo_campa_a_dto_google_business_profile', name: 'JPG fondo sólido (logo campaña + dto.)', size: '1920x1080', width: 1920, height: 1080, format: 'img', channel: 'GOOGLE BUSINESS PROFILE', seconds: 'na', maxFileSize: 150 },
    { id: 'white_portugal_hotels', name: 'White', size: '2560x1440', width: 2560, height: 1440, format: 'img', channel: 'PORTUGAL HOTELS', seconds: 'na', maxFileSize: 150 },
    { id: 'jpg_portugal_hotels', name: 'JPG', size: '1121x900', width: 1121, height: 900, format: 'img', channel: 'PORTUGAL HOTELS', seconds: 'na', maxFileSize: 150 },
    { id: 'white_cuadrado_portugal_hotels', name: 'White cuadrado', size: '500x500', width: 500, height: 500, format: 'img', channel: 'PORTUGAL HOTELS', seconds: 'na', maxFileSize: 150 },
    { id: 'white_vertical_portugal_hotels', name: 'White vertical', size: '768x1500', width: 768, height: 1500, format: 'img', channel: 'PORTUGAL HOTELS', seconds: 'na', maxFileSize: 150 },
    { id: 'app_imagen_limpia_promo_app', name: 'APP (imagen limpia)', size: '2160x3840', width: 2160, height: 3840, format: 'img', channel: 'PROMO APP', seconds: 'na', maxFileSize: 150 },
    { id: 'banner_carrusel_portada_imagen_limpia_portal_empleado', name: 'Banner carrusel portada (imagen limpia)', size: '1170x500', width: 1170, height: 500, format: 'img', channel: 'PORTAL EMPLEADO', seconds: 'na', maxFileSize: 150 },
    { id: 'banner_miniatura_noticias_portal_empleado', name: 'Banner miniatura noticias', size: '274x154', width: 274, height: 154, format: 'img', channel: 'PORTAL EMPLEADO', seconds: 'na', maxFileSize: 150 },
    { id: 'banner_est_tico_portal_empleado', name: 'Banner estático', size: '680x370', width: 680, height: 370, format: 'img', channel: 'PORTAL EMPLEADO', seconds: 'na', maxFileSize: 150 },
    { id: 'newsfeed_imagen_limpia_portal_empleado', name: 'Newsfeed (imagen limpia)', size: '300x300', width: 300, height: 300, format: 'img', channel: 'PORTAL EMPLEADO', seconds: 'na', maxFileSize: 150 },
    { id: 'banner_carrusel_portada_portal_empleado', name: 'Banner carrusel portada', size: '1204x250', width: 1204, height: 250, format: 'img', channel: 'PORTAL EMPLEADO', seconds: 'na', maxFileSize: 150 },
    { id: 'ctrip_meituan_flagship_store_banner_ota_apac', name: 'Ctrip & Meituan Flagship Store Banner', size: '1125x531', width: 1125, height: 531, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'meituan_flagship_store_brandzone_banner_ota_apac', name: 'Meituan Flagship Store Brandzone Banner', size: '710x380', width: 710, height: 380, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'wechat_ota_apac', name: 'WeChat', size: '750x556', width: 750, height: 556, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'wechat_psd_ota_apac', name: 'WeChat + PSD', size: '768x1024', width: 768, height: 1024, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'wechat_psd_ota_apac', name: 'WeChat + PSD', size: '1280x720', width: 1280, height: 720, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'baidu_sem_pc_sitelink_ota_apac', name: 'Baidu SEM PC Sitelink', size: '1200x400', width: 1200, height: 400, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
    { id: 'baidu_sem_mobile_sitelink_ota_apac', name: 'Baidu SEM Mobile Sitelink', size: '518x292', width: 518, height: 292, format: 'img', channel: 'OTA / APAC', seconds: 'na', maxFileSize: 150 },
];
